// Estilos modulares para el Modal
export const estiloModal = {
  overlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    background: 'rgba(0,0,0,0.25)',
    zIndex: 1000,
    display: 'flex' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  modal: {
    background: '#fff',
    borderRadius: 12,
    padding: 0,
    minWidth: 350,
    maxWidth: 500,
    maxHeight: '90vh',
    boxShadow: '0 4px 24px rgba(0,0,0,0.12)',
    position: 'relative' as const,
    display: 'flex' as const,
    flexDirection: 'column' as const,
  },
  closeBtn: {
    position: 'absolute' as const,
    top: 12,
    right: 12,
    background: 'none',
    border: 'none',
    fontSize: 22,
    cursor: 'pointer',
    zIndex: 2,
  },
  content: {
    padding: 32,
    overflowY: 'auto' as const,
    maxHeight: '90vh',
    minHeight: 0,
  },
};
