// Estilos modulares para tablas y secciones
export const estiloTablas = {
  equiposSection: {
    background: '#fff',
    borderRadius: 12,
    boxShadow: '0 4px 16px rgba(30,41,59,0.10)',
    overflow: 'hidden',
    marginTop: '2.5rem',
    maxWidth: 1200,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  sectionHeader: {
    display: 'flex' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    padding: '1.5rem 2rem',
    borderBottom: '2px solid #2563eb',
    background: '#f8fafc',
  },
  sectionHeaderH3: {
    fontSize: '1.3rem',
    fontWeight: 800,
    color: '#2563eb',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  tableContainer: {
    overflowX: 'auto' as const,
  },
  equiposTable: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '1rem',
    background: '#f8fafc',
    boxShadow: '0 2px 8px rgba(30,41,59,0.07)',
    borderRadius: 10,
    overflow: 'hidden',
  },
  equiposTableTh: {
    backgroundColor: '#2563eb',
    padding: '1rem',
    textAlign: 'left' as const,
    fontWeight: 700,
    color: '#fff',
    borderBottom: '2px solid #38bdf8',
    letterSpacing: '0.5px',
    fontSize: '1.05rem',
    borderTop: 'none',
  },
  equiposTableTd: {
    padding: '1rem',
    borderBottom: '1px solid #e2e8f0',
    verticalAlign: 'middle' as const,
    background: '#fff',
    fontSize: '1rem',
  },
  equipoRow: {
    borderLeft: '4px solid #007bff',
    transition: 'border-color 0.2s',
  },
  equipoRowHover: {
    borderLeft: '4px solid #0056b3',
  },
  badgeTipo: {
    display: 'inline-block',
    background: '#38bdf8',
    color: '#fff',
    fontSize: '0.9rem',
    fontWeight: 700,
    padding: '0.3rem 1rem',
    borderRadius: 20,
    boxShadow: '0 1px 2px rgba(56, 189, 248, 0.10)',
    letterSpacing: '0.5px',
    transition: 'all 0.2s',
  },
};
